version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    container_name: flask-app
    ports:
      - 4800:4800
  redis:
    container_name: redis-db
    image: "redis:alpine"
    ports:
      - 6379

